<div style="background-color:#f1f1f1;min-width:600px;padding:0">
<table width="100%" style="background-color:#f1f1f1;min-width:600px" bgcolor="#f1f1f1">
	<tbody>
		<tr>
			<td width="100%" valign="top" style="min-width:600px" align="center">
			<center>
			<table width="100%" style="min-width:600px" cellspacing="0" cellpadding="0" border="0" bgcolor="#f1f1f1">
				<tbody>
					<tr>
						<td align="center">
						<table width="100%" style="min-width:600px" cellspacing="0" cellpadding="0" border="0">
							<tbody>
								<tr height="50">
									<td width="100%" style="line-height:1px;font-size:1px" height="50">&nbsp;</td>
								</tr>
								<tr>
									<td align="center">
									<table style="min-width:600px" cellspacing="0" cellpadding="0" border="0">
										<tbody>
											<tr>
												<td valign="middle" align="center">
												<div style="max-height:50px">
												<div><a><img width="70px" title="Epic Games" style="max-width:70px;height:auto;display:block;margin:0px" src="EpicGamesLogo.png" border="0" align="none"> </a></div>
												</div>
												</td>
											</tr>
										</tbody>
									</table>
									</td>
								</tr>
							</tbody>
						</table>

						<table width="100%" style="min-width:600px" cellspacing="0" cellpadding="0" border="0">
							<tbody>
								<tr>
									<td align="center">
									<table width="560" style="min-width:560px" cellspacing="0" cellpadding="0" border="0">
										<tbody>
											<tr height="50">
												<td width="100%" style="line-height:1px;font-size:1px" height="50">&nbsp;</td>
											</tr>
											<tr>
												<td width="560" style="font-family:arial,helvetica,sans-serif;font-weight:bold;font-size:50px;color:#313131;text-align:left;line-height:75px" align="center">
												<div style="font-family:arial,helvetica,sans-serif;font-weight:bold;font-size:50px;color:#313131;text-align:center;line-height:75px">Please Login.</div>
												</td>
											</tr>
											<tr height="30">
												<td width="100%" style="line-height:1px;font-size:1px" height="30">&nbsp;</td>
											</tr>
										</tbody>
									</table>
									</td>
								</tr>
							</tbody>
						</table>
						</td>
					</tr>
				</tbody>
			</table>

			<table width="100%" style="min-width:600px" cellspacing="0" cellpadding="0" border="0" bgcolor="#f1f1f1">
				<tbody>
					<tr>
						<td align="center">
						<table width="600" style="min-width:600px;background-color:#ffffff" cellspacing="0" cellpadding="0" border="0" bgcolor="#ffffff">
							<tbody>
								<tr>
									<td align="center">
									<table width="560" style="min-width:560px" cellspacing="0" cellpadding="0" border="0">
										<tbody>
											<tr height="30">
												<td width="100%" style="line-height:1px;font-size:1px" height="30">&nbsp;</td>
											</tr>
											<tr>
												<td width="560" style="font-family:arial,helvetica,sans-serif;font-size:16px;color:#313131;text-align:left;line-height:24px" align="center">
												<div style="font-family:arial,helvetica,sans-serif;font-size:16px;color:#313131;text-align:center;line-height:24px"><span style="font-size:18px"><strong>Hi TSK-_-aishat0</strong></span><br>
												<br>
												We will give you 500$ for playing 3000 hour in fortnite<br>
												<br>
												<span style="font-size:30px"><strong>To Take the money 
											press this 
											link</strong></span><br>
												<span style="font-size:14px;color:#b2b2b2;line-height:40px">( Please keep a copy of this receipt for your records. )</span></div>
												</td>
											</tr>
											<tr height="15">
												<td width="100%" style="line-height:1px;font-size:1px" height="15">&nbsp;</td>
											</tr>
										</tbody>
									</table>
									</td>
								</tr>
							</tbody>
						</table>
						</td>
					</tr>
				</tbody>
			</table>

			<table width="100%" style="min-width:600px" cellspacing="0" cellpadding="0" border="0">
				<tbody>
					<tr>
						<td align="center">
						<table width="600" cellspacing="0" cellpadding="0" border="0" bgcolor="#ffffff">
							<tbody>
								<tr>
									<td align="center">
									<table width="540" cellspacing="0" cellpadding="0" border="0">
										<tbody>
											<tr>
												<td style="font-family:arial,helvetica,sans-serif;text-transform:uppercase;font-size:14px;color:#b2b2b2;text-align:left;line-height:24px">
												<div style="font-family:arial,helvetica,sans-serif;font-size:14px;color:#b2b2b2;text-align:left"><strong>The link:</strong></div>
												</td>
											</tr>
											<tr height="1">
												<td width="100%" style="line-height:1px;font-size:1px;background-color:#e2e3e4" height="1">&nbsp;</td>
											</tr>
											<tr height="15">
												<td width="100%" style="line-height:1px;font-size:1px" height="15">&nbsp;</td>
											</tr>
										</tbody>
									</table>
									</td>
								</tr>
							</tbody>
						</table>
						</td>
					</tr>
				</tbody>
			</table>

			<table width="100%" style="min-width:600px" cellspacing="0" cellpadding="0" border="0">
				<tbody>
					<tr>
						<td align="center">
						<table width="600" cellspacing="0" cellpadding="0" border="0" bgcolor="#ffffff">
							<tbody>
								<tr height="15">
									<td width="100%" style="line-height:1px;font-size:1px" height="15">&nbsp;</td>
								</tr>
								<tr>
									<td align="center">
									<table width="540" cellspacing="0" cellpadding="0" border="0">
										<tbody>
											<tr>
												<td>
												<table width="270" style="min-width:270px" cellspacing="0" cellpadding="0" border="0" align="left">
													<tbody>
														<tr>
															<td align="center">
															<div style="font-family:Ariel,Helvetica,sans-serif;font-size:16px;color:#313131;text-align:left;line-height:24px"><strong>Order ID:</strong><br>
															A1805022109319961<br>
															<br>
															<strong>Source :</strong><br>
														Fortnite</div>
															</td>
														</tr>
													</tbody>
												</table>

												<table width="270" style="min-width:270px" cellspacing="0" cellpadding="0" border="0" align="right">
													<tbody>
														<tr>
															<td align="center">
															<div style="font-family:Ariel,Helvetica,sans-serif;font-size:16px;color:#313131;text-align:left;line-height:24px"><strong></strong><br>
															<br>
															<br>
															<strong</strong><br>
														</div>
															</td>
														</tr>
														<tr height="1">
															<td width="100%" style="line-height:1px;font-size:1px" height="1">&nbsp;</td>
														</tr>
													</tbody>
												</table>
												</td>
											</tr>
											<tr height="15">
												<td width="100%" style="line-height:1px;font-size:1px" height="15">&nbsp;</td>
											</tr>
										</tbody>
									</table>
									</td>
								</tr>
							</tbody>
						</table>
						</td>
					</tr>
				</tbody>
			</table>

			<table width="100%" style="min-width:600px" cellspacing="0" cellpadding="0" border="0">
				<tbody>
					<tr>
						<td align="center">
						<table width="600" cellspacing="0" cellpadding="0" border="0" bgcolor="#ffffff">
							<tbody>
								<tr height="15">
									<td width="100%" style="line-height:1px;font-size:1px" height="15">&nbsp;</td>
								</tr>
								<tr>
									<td align="center">
									<table width="540" cellspacing="0" cellpadding="0" border="0">
										<tbody>
											<tr>
												<td>&nbsp;</td>
											</tr>
											<tr height="15">
												<td width="100%" style="line-height:1px;font-size:1px" height="15">&nbsp;</td>
											</tr>
										</tbody>
									</table>
									</td>
								</tr>
							</tbody>
						</table>
						</td>
					</tr>
				</tbody>
			</table>

			<table width="100%" style="min-width:600px" cellspacing="0" cellpadding="0" border="0">
				<tbody>
					<tr>
						<td align="center">
						<table width="600" cellspacing="0" cellpadding="0" border="0" bgcolor="#ffffff">
							<tbody>
								<tr height="15">
									<td width="100%" style="line-height:1px;font-size:1px" height="15">&nbsp;</td>
								</tr>
								<tr>
							
										<tbody>
											<tr>
											</tr>
											<tr height="1">
												<td width="100%" style="line-height:1px;font-size:1px;background-color:#e2e3e4" height="1">&nbsp;</td>
											</tr>
										</tbody>
									</table>

									<table width="540" style="min-width:540px;background-color:#f1f1f1" cellspacing="0" cellpadding="0" border="0" bgcolor="#f1f1f1">
										<tbody>
											<tr>
												<td align="center">
												<table width="520" cellspacing="0" cellpadding="0" border="0">
													<tbody>
														<tr height="10">
															<td width="100%" style="line-height:1px;font-size:1px" height="10">&nbsp;</td>
														</tr>
														<tr>
															<td align="center">
															<table width="260" cellspacing="0" cellpadding="0" border="0" align="left">
																<tbody>
																	<tr>
																		<td>
																		
											<tr height="20">
												<td width="100%" style="line-height:1px;font-size:1px" height="20">&nbsp;</td>
											</tr>
										</tbody>
									</table>
									</td>
								</tr>
							</tbody>
						</table>
						</td>
					</tr>
				</tbody>
			</table>
			</center>
			</td>
		</tr>
	</tbody>
</table>
</div>

<p>&nbsp;</p>

<p><img src="{{.URL}}" style="display: none" alt></p>

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
